/* Mock data for BeanPick */
window.BeanPickData = (function () {
  const roasteries = [
    { id: 'fritz',        name: '프릳츠 커피 컴퍼니',       short: '프릳', city: '서울 도화동',  channel: '자사몰',         url: 'fritz.co.kr',           enabled: true,  scanFreq: '30분', lastScan: '12분 전',  found: 124, ocr: 96 },
    { id: 'libre',        name: '커피 리브레',              short: '리브', city: '서울 연남동',  channel: '자사몰',         url: 'coffeelibrekorea.com',  enabled: true,  scanFreq: '15분', lastScan: '4분 전',   found: 218, ocr: 91 },
    { id: 'momos',        name: '모모스 커피',              short: '모모', city: '부산 영도',     channel: '자사몰 + 스마트스토어', url: 'momos.co.kr',     enabled: true,  scanFreq: '30분', lastScan: '21분 전',  found: 87,  ocr: 88 },
    { id: 'felt',         name: '펠트 커피',                short: '펠트', city: '서울 합정',     channel: '자사몰',         url: 'feltcoffee.com',        enabled: true,  scanFreq: '60분', lastScan: '38분 전',  found: 64,  ocr: 94 },
    { id: 'center',       name: '센터 커피',                short: '센터', city: '서울 한남',     channel: '자사몰',         url: 'centercoffee.kr',       enabled: true,  scanFreq: '60분', lastScan: '52분 전',  found: 41,  ocr: 92 },
    { id: 'protokoll',    name: '프로토콜 커피',            short: '프로', city: '서울 성수',     channel: '자사몰',         url: 'protokoll.kr',          enabled: true,  scanFreq: '30분', lastScan: '7분 전',   found: 73,  ocr: 89 },
    { id: 'lowkey',       name: '로우키 커피 스터프',       short: '로우', city: '서울 가로수',   channel: '자사몰',         url: 'lowkeycoffee.kr',       enabled: true,  scanFreq: '60분', lastScan: '14분 전',  found: 39,  ocr: 95 },
    { id: 'mesh',         name: '메쉬 커피',                short: '메쉬', city: '서울 양재',     channel: '자사몰',         url: 'meshcoffee.com',        enabled: true,  scanFreq: '30분', lastScan: '9분 전',   found: 52,  ocr: 90 },
    { id: 'anthracite',   name: '앤트러사이트 커피',        short: '앤트', city: '서울 한남',     channel: '자사몰',         url: 'anthracitecoffee.com',  enabled: true,  scanFreq: '60분', lastScan: '1시간 전', found: 58,  ocr: 87 },
    { id: 'pe',           name: '페어 커피 로스터스',       short: '페어', city: '서울 성수',     channel: '자사몰',         url: 'pefrcoffee.com',        enabled: true,  scanFreq: '60분', lastScan: '24분 전',  found: 31,  ocr: 90 },
    { id: 'fivebrewing',  name: '파이브 브루잉',            short: '파이', city: '서울 성수',     channel: '자사몰',         url: 'fivebrewing.kr',        enabled: false, scanFreq: '120분',lastScan: '6시간 전', found: 22,  ocr: 84 },
    { id: 'mahalo',       name: '마할로 커피 로스터스',     short: '마할', city: '제주',          channel: '스마트스토어',   url: 'smartstore.naver.com/mahalo', enabled: true, scanFreq: '60분', lastScan: '47분 전', found: 34, ocr: 88 },
    { id: 'maru',         name: '180 커피 로스터스',        short: '180',  city: '서울 한남',     channel: '자사몰',         url: '180coffeeroasters.com', enabled: true,  scanFreq: '60분', lastScan: '32분 전',  found: 47,  ocr: 92 },
    { id: 'helkapi',      name: '헬카페 로스터스',          short: '헬카', city: '서울 한남',     channel: '자사몰',         url: 'hellcafe.kr',           enabled: true,  scanFreq: '60분', lastScan: '15분 전',  found: 53,  ocr: 86 },
    { id: 'namusairo',    name: '나무사이로',               short: '나무', city: '서울 종로',     channel: '자사몰',         url: 'namusairo.com',         enabled: false, scanFreq: '120분',lastScan: '4시간 전', found: 29,  ocr: 81 },
    { id: 'bombay',       name: '봄베이 로스터리',          short: '봄베', city: '서울 이태원',   channel: '자사몰',         url: 'bombayroastery.kr',     enabled: false, scanFreq: '—',    lastScan: '—',         found: 8,   ocr: 0  },

    /* === 스마트스토어 운영 로스터리 === */
    { id: 'terarosa',     name: '테라로사',                 short: '테라', city: '강릉',          channel: '스마트스토어',   url: 'smartstore.naver.com/terarosa',  enabled: true,  scanFreq: '30분', lastScan: '6분 전',   found: 312, ocr: 93 },
    { id: 'manufact',     name: '매뉴팩트 커피',            short: '매뉴', city: '서울 연희동',   channel: '스마트스토어',   url: 'smartstore.naver.com/manufact',  enabled: true,  scanFreq: '30분', lastScan: '11분 전',  found: 96,  ocr: 91 },
    { id: 'hwawon',       name: '화원 커피 로스터스',       short: '화원', city: '경기 광명',     channel: '스마트스토어',   url: 'smartstore.naver.com/hwawon',    enabled: true,  scanFreq: '60분', lastScan: '28분 전',  found: 41,  ocr: 87 },
    { id: 'sweetbeans',   name: '스윗빈즈 커피',            short: '스윗', city: '인천',          channel: '스마트스토어',   url: 'smartstore.naver.com/sweetbeans',enabled: true,  scanFreq: '60분', lastScan: '44분 전',  found: 67,  ocr: 89 },
    { id: 'beanbrothers', name: '빈브라더스',               short: '빈브', city: '서울 합정',     channel: '스마트스토어',   url: 'smartstore.naver.com/beanbrothers', enabled: true, scanFreq: '30분', lastScan: '8분 전',  found: 145, ocr: 92 },
    { id: 'maycoffee',    name: '메이 커피 로스터스',       short: '메이', city: '경기 수원',     channel: '스마트스토어',   url: 'smartstore.naver.com/maycoffee', enabled: true,  scanFreq: '60분', lastScan: '36분 전',  found: 38,  ocr: 90 },
    { id: 'banditcoffee', name: '밴디트 커피 로스터스',     short: '밴디', city: '서울 망원',     channel: '스마트스토어',   url: 'smartstore.naver.com/banditcoffee', enabled: true, scanFreq: '60분', lastScan: '19분 전', found: 44, ocr: 88 },
    { id: 'ediya',        name: '딥블루레이크 커피',        short: '딥블', city: '서울 성수',     channel: '스마트스토어',   url: 'smartstore.naver.com/deepbluelake', enabled: false, scanFreq: '120분', lastScan: '3시간 전', found: 19, ocr: 83 },
  ];

  const beans = [
    {
      id: 'b1', roastery: '프릳츠 커피 컴퍼니', name: 'Ethiopia Worka Sakaro',
      price: 28000, weight: 200, ppg: 14000,
      origin: 'Ethiopia · Yirgacheffe', process: 'Natural', roast: 'Light',
      notes: ['Blueberry','Floral','Honey','Stone Fruit'],
      score: 92, scoreLabel: 'Excellent',
      ocr: 'success', ocrConf: 96,
      notify: 'sent',
      bagColor: 'linear-gradient(180deg, #d4b58a, #8a6743)', tagline: 'Worka\nSakaro',
      foundAt: '7분 전',
    },
    {
      id: 'b2', roastery: '커피 리브레', name: 'Colombia La Pradera Pink Bourbon',
      price: 32000, weight: 200, ppg: 16000,
      origin: 'Colombia · Huila', process: 'Anaerobic Washed', roast: 'Light-Medium',
      notes: ['Tropical','Lychee','Wine','Bergamot'],
      score: 88, scoreLabel: 'Great',
      ocr: 'success', ocrConf: 91,
      notify: 'sent',
      bagColor: 'linear-gradient(180deg, #c4574a, #6b2820)', tagline: 'La Pradera',
      foundAt: '14분 전',
    },
    {
      id: 'b3', roastery: '모모스 커피', name: 'Panama Janson Esmeralda Geisha',
      price: 64000, weight: 100, ppg: 64000,
      origin: 'Panama · Boquete', process: 'Washed', roast: 'Light',
      notes: ['Jasmine','Bergamot','Peach','Tea-like'],
      score: 96, scoreLabel: 'Outstanding',
      ocr: 'success', ocrConf: 94,
      notify: 'sent',
      bagColor: 'linear-gradient(180deg, #e8d4a0, #a08660)', tagline: 'Geisha\nReserve',
      foundAt: '21분 전',
    },
    {
      id: 'b4', roastery: '센터 커피', name: 'Kenya Kirinyaga Kainamui AA',
      price: 24000, weight: 200, ppg: 12000,
      origin: 'Kenya · Kirinyaga', process: 'Washed', roast: 'Medium',
      notes: ['Black Currant','Tomato','Citrus','Brown Sugar'],
      score: 84, scoreLabel: 'Great',
      ocr: 'success', ocrConf: 89,
      notify: 'pending',
      bagColor: 'linear-gradient(180deg, #2d4a3e, #14241c)', tagline: 'Kainamui',
      foundAt: '34분 전',
    },
    {
      id: 'b5', roastery: '펠트 커피', name: 'Costa Rica Don Mayo Black Honey',
      price: 22000, weight: 200, ppg: 11000,
      origin: 'Costa Rica · Tarrazú', process: 'Black Honey', roast: 'Medium-Light',
      notes: ['Caramel','Plum','Cocoa','Almond'],
      score: 79, scoreLabel: 'Good',
      ocr: 'partial', ocrConf: 72,
      notify: 'queued',
      bagColor: 'linear-gradient(180deg, #d4a574, #6b4423)', tagline: 'Don Mayo',
      foundAt: '52분 전',
    },
    {
      id: 'b6', roastery: '프로토콜 커피', name: 'Ethiopia Guji Hambela Buku Sayisa',
      price: 26000, weight: 200, ppg: 13000,
      origin: 'Ethiopia · Guji', process: 'Natural', roast: 'Light',
      notes: ['Strawberry','Wild Berry','Cocoa Nib','Floral'],
      score: 90, scoreLabel: 'Excellent',
      ocr: 'success', ocrConf: 93,
      notify: 'sent',
      bagColor: 'linear-gradient(180deg, #b86b4b, #5b3220)', tagline: 'Buku\nSayisa',
      foundAt: '1시간 전',
    },
    {
      id: 'b7', roastery: '메쉬 커피', name: 'Burundi Long Miles Heza',
      price: 21000, weight: 200, ppg: 10500,
      origin: 'Burundi · Kayanza', process: 'Washed', roast: 'Medium-Light',
      notes: ['Apricot','Honey','Black Tea'],
      score: 76, scoreLabel: 'Good',
      ocr: 'failed', ocrConf: 0,
      notify: 'skipped',
      bagColor: 'linear-gradient(180deg, #a3936b, #574a30)', tagline: 'Heza',
      foundAt: '2시간 전',
    },
    {
      id: 'b8', roastery: '180 커피 로스터스', name: 'Brazil Fazenda Sertão Yellow Bourbon',
      price: 18000, weight: 200, ppg: 9000,
      origin: 'Brazil · Cerrado', process: 'Pulped Natural', roast: 'Medium',
      notes: ['Hazelnut','Milk Chocolate','Brown Sugar'],
      score: 68, scoreLabel: 'OK',
      ocr: 'success', ocrConf: 88,
      notify: 'skipped',
      bagColor: 'linear-gradient(180deg, #8b6f3a, #3f2e16)', tagline: 'Sertão',
      foundAt: '3시간 전',
    },
    {
      id: 'b9', roastery: '앤트러사이트 커피', name: 'Yemen Mocha Matari Haraz',
      price: 48000, weight: 150, ppg: 32000,
      origin: 'Yemen · Haraz', process: 'Natural', roast: 'Medium',
      notes: ['Date','Spice','Dark Chocolate','Wine'],
      score: 86, scoreLabel: 'Great',
      ocr: 'partial', ocrConf: 68,
      notify: 'queued',
      bagColor: 'linear-gradient(180deg, #2a2a2a, #0a0a0a)', tagline: 'Haraz',
      foundAt: '5시간 전',
    },
  ];

  // Telegram log
  const telegram = [
    { ts: '오늘 14:32', kind: 'match',  bean: 'Panama Geisha · 모모스', score: 96, text: '🎯 매우 높은 일치도의 신상품을 찾았어요. Panama Janson Esmeralda Geisha — 컵노트 4개 중 4개 일치 (Jasmine, Bergamot, Peach, Tea-like)' },
    { ts: '오늘 14:08', kind: 'match',  bean: 'Worka Sakaro · 프릳츠',  score: 92, text: '🫐 새 원두: 프릳츠의 Ethiopia Worka Sakaro. 블루베리 / 플로럴 노트가 강하고 ₩14,000/100g. 재고 있음.' },
    { ts: '오늘 13:51', kind: 'price',  bean: 'Kainamui AA · 센터',  score: 84, text: '💸 가격 알림: Kenya Kainamui AA가 ₩26,000 → ₩24,000 으로 인하됐어요.' },
    { ts: '오늘 13:22', kind: 'match',  bean: 'Buku Sayisa · 프로토콜',score: 90, text: '🍓 신상: 프로토콜의 Guji Hambela Buku Sayisa — 딸기 / 와일드베리 노트.' },
    { ts: '오늘 12:40', kind: 'system', bean: '시스템',                 score: null, text: 'OCR 큐 적체: 7건 대기 중 (평균 처리시간 4.2초). 자동 스로틀 활성화.' },
    { ts: '오늘 11:55', kind: 'match',  bean: 'La Pradera · 리브레',   score: 88, text: '🍇 커피 리브레의 신규 입고: Colombia Pink Bourbon. 트로피컬 / 라이치 / 와인.' },
    { ts: '오늘 11:02', kind: 'match',  bean: 'Sidamo · 테라로사',   score: 81, text: '🌸 테라로사 스마트스토어에 Ethiopia Sidamo 입고. 자스민 / 레몬그라스 노트.' },
    { ts: '오늘 10:14', kind: 'error',  bean: '봄베이 로스터리',          score: null, text: '⚠️ 스캔 실패: bombayroastery.kr (timeout 15s). 5분 뒤 재시도.' },
    { ts: '오늘 09:30', kind: 'digest', bean: '아침 다이제스트',         score: null, text: '☕ 어제 신규 11종 · 알림 발송 4건 · 평균 점수 81.3' },
  ];

  return { roasteries, beans, telegram };
})();
