# Reviewer A (current visible, original batch order) — batch 13
# current is reference only; evidence (원문) is authoritative. Not anchored on current.
import json

def F(value, raw, confidence, evidence, evidenceSource, evidenceKind=None):
    d = {"value": value, "raw": raw, "confidence": confidence,
         "evidence": evidence, "evidenceSource": evidenceSource}
    if evidenceKind:
        d["evidenceKind"] = evidenceKind
    return d

def G(**kw):
    return {"golden": kw}

A = {}

# 1) cafedoan-7632387865 (MANHATTAN Ethiopia Shoondisa Natural)
# current: country=에티오피아, process=내추럴, notes=['딸기'] — '딸기'는 충돌한 OCR에서 유래, 원문 확정 불가
A["cafedoan-7632387865"] = G(
    productType=F("single", "MANHATTAN 맨해튼 Ethiopia Shoondisa Natural", "HIGH",
        "단일 산지(Ethiopia) 명시",
        "audit-input/products/cafedoan-7632387865-0aaa1e62.json#snapshotRecord.productName"),
    status=F("soldout", "soldout", "MEDIUM", "isSoldOut=true (수집 플래그), 반대 증거 없음", "collector_flag"),
    originCountry=F("에티오피아", "Ethiopia", "HIGH",
        "상품명 'Ethiopia Shoondisa Natural'",
        "audit-input/products/cafedoan-7632387865-0aaa1e62.json#snapshotRecord.productName"),
    originRegion=F(None, "Shoondisa", "SOURCE_MISSING",
        "'Shoondisa'는 워싱스테이션명 — 지역 승격 금지",
        "audit-input/products/cafedoan-7632387865-0aaa1e62.json#snapshotRecord.productName"),
    producer=F(None, "Shoondisa", "SOURCE_MISSING",
        "'Shoondisa'는 워싱스테이션 — 생산자가 아니므로 제외 (초르소 선례)",
        "audit-input/products/cafedoan-7632387865-0aaa1e62.json#snapshotRecord.productName"),
    process=F("내추럴", "Natural", "HIGH",
        "상품명 'Natural' 명시",
        "audit-input/products/cafedoan-7632387865-0aaa1e62.json#snapshotRecord.productName"),
    variety=F(None, None, "SOURCE_MISSING", "원문 확인했으나 품종 정보 없음",
        "audit-input/products/cafedoan-7632387865-0aaa1e62.json#snapshotRecord.productName"),
    roast=F(None, None, "SOURCE_MISSING", "원문 확인했으나 로스팅 정보 없음",
        "audit-input/products/cafedoan-7632387865-0aaa1e62.json#snapshotRecord.productName"),
    tastingNotes=F(None,
        ["Peach, Jasmine, Earl Grey, Honey (이미지 f80_80)",
         "berry compote, strawberry juice, white sugar, round mouthfeel (이미지 f750_750)"], "UNKNOWN",
        "동일 이미지의 해상도 변형 간 OCR 정면 충돌 — 원문 이미지 없이는 해결 불가 → CASE 3. current의 '딸기'(strawberry juice 유래 추정)는 충돌한 OCR에서 온 것으로 원문 확정 불가하여 미채택",
        "audit-input/products/cafedoan-7632387865-0aaa1e62.json#evidence.ocr"),
)

# 2) hocuspocus-10781774331 (콜롬비아 벨라 알레한드리아 게이샤 애너로빅 워시드)
# current: process=워시드, variety=게이샤 — 원문 '애너로빅 워시드'의 핵심 가공은 워시드 (§8 수식어 규정)
A["hocuspocus-10781774331"] = G(
    productType=F("single", "콜롬비아 벨라 알레한드리아 게이샤 애너로빅 워시드", "HIGH",
        "단일 산지(콜롬비아) 명시",
        "audit-input/products/hocuspocus-10781774331-a7ff0e77.json#snapshotRecord.productName"),
    status=F("active", "active", "MEDIUM", "isSoldOut=false (수집 플래그), 반대 증거 없음", "collector_flag"),
    originCountry=F("콜롬비아", "콜롬비아", "HIGH",
        "상품명 '콜롬비아 벨라 알레한드리아 게이샤 애너로빅 워시드'",
        "audit-input/products/hocuspocus-10781774331-a7ff0e77.json#snapshotRecord.productName"),
    originRegion=F(None, "벨라 알레한드리아", "SOURCE_MISSING",
        "'벨라 알레한드리아'는 농장명 — 지역 승격 금지",
        "audit-input/products/hocuspocus-10781774331-a7ff0e77.json#snapshotRecord.productName"),
    producer=F("벨라 알레한드리아", "벨라 알레한드리아", "MEDIUM",
        "상품명 농장명 추정 (엘 파라이소 선례)",
        "audit-input/products/hocuspocus-10781774331-a7ff0e77.json#snapshotRecord.productName"),
    process=F("워시드", "애너로빅 워시드", "HIGH",
        "§8: 애너로빅=가공 수식어(단독 가공 아님) — 핵심 가공은 워시드. 원문 '애너로빅 워시드'",
        "audit-input/products/hocuspocus-10781774331-a7ff0e77.json#snapshotRecord.productName"),
    variety=F("게이샤", "게이샤", "HIGH",
        "상품명 '게이샤' 명시",
        "audit-input/products/hocuspocus-10781774331-a7ff0e77.json#snapshotRecord.productName"),
    roast=F(None, None, "SOURCE_MISSING", "원문 확인했으나 로스팅 정보 없음",
        "audit-input/products/hocuspocus-10781774331-a7ff0e77.json#snapshotRecord.productName"),
    tastingNotes=F([], [], "SOURCE_MISSING", "원문 확인했으나 노트 정보 없음",
        "audit-input/products/hocuspocus-10781774331-a7ff0e77.json#snapshotRecord.productName"),
)

# 3) 루비아커피-과테말라엘소코로파카마라워시드라이트로스트
# current: variety=파카마라, notes=['블루베리','캐러멜','자몽'] — 노트는 충돌한 OCR 유래이므로 미채택
A["루비아커피-과테말라엘소코로파카마라워시드라이트로스트"] = G(
    productType=F("single", "과테말라 엘 소코로 파카마라 워시드 라이트 로스트", "HIGH",
        "단일 산지(과테말라) 명시",
        "audit-input/products/루비아커피-과테말라엘소코로파카마라워시드라이트로스트-90b33c19.json#snapshotRecord.productName"),
    status=F("soldout", "soldout", "MEDIUM", "isSoldOut=true (수집 플래그), 반대 증거 없음", "collector_flag"),
    originCountry=F("과테말라", "과테말라", "HIGH",
        "상품명 '과테말라 엘 소코로 파카마라 워시드 라이트 로스트'",
        "audit-input/products/루비아커피-과테말라엘소코로파카마라워시드라이트로스트-90b33c19.json#snapshotRecord.productName"),
    originRegion=F(None, "엘 소코로", "SOURCE_MISSING",
        "'엘 소코로'는 농장명으로 추정 — 지역 승격 금지",
        "audit-input/products/루비아커피-과테말라엘소코로파카마라워시드라이트로스트-90b33c19.json#snapshotRecord.productName"),
    producer=F("엘 소코로", "엘 소코로", "MEDIUM",
        "상품명 농장명 추정 (엘 파라이소 선례)",
        "audit-input/products/루비아커피-과테말라엘소코로파카마라워시드라이트로스트-90b33c19.json#snapshotRecord.productName"),
    process=F("워시드", "워시드", "HIGH",
        "상품명 '워시드' 명시",
        "audit-input/products/루비아커피-과테말라엘소코로파카마라워시드라이트로스트-90b33c19.json#snapshotRecord.productName"),
    variety=F("파카마라", "파카마라", "HIGH",
        "상품명 '파카마라' 명시",
        "audit-input/products/루비아커피-과테말라엘소코로파카마라워시드라이트로스트-90b33c19.json#snapshotRecord.productName"),
    roast=F("Light", "라이트 로스트", "HIGH",
        "상품명 '라이트 로스트' — 5단계 매핑표 Light",
        "audit-input/products/루비아커피-과테말라엘소코로파카마라워시드라이트로스트-90b33c19.json#snapshotRecord.productName"),
    tastingNotes=F(None,
        ["Blueberry, Strawberry, Floral, Sweet, Clean (이미지A f80_80)",
         "블루베리, 카라멜, 시럽 (이미지A f750_750)",
         "자몽, 블루베리, 캐러멜, 시럽 (이미지B f750_750)"], "UNKNOWN",
        "동일 이미지(A)의 해상도 변형 간 OCR 정면 충돌 → CASE 3. current의 노트(블루베리·캐러멜·자몽)는 충돌한 OCR에서 온 것으로 원문 확정 불가하여 미채택",
        "audit-input/products/루비아커피-과테말라엘소코로파카마라워시드라이트로스트-90b33c19.json#evidence.ocr"),
)

# 4) fillout-13732632561 (베트남 록렁 엑셀사 원두)
# current: 전부 비어 있음 — 원문 '엑셀사'는 종(species)이지 품종(variety)이 아니므로 제외
A["fillout-13732632561"] = G(
    productType=F("single", "베트남 록렁 엑셀사 원두", "HIGH",
        "단일 산지(베트남) 명시",
        "audit-input/products/fillout-13732632561-6d9a976d.json#snapshotRecord.productName"),
    status=F("active", "active", "MEDIUM", "isSoldOut=false (수집 플래그), 반대 증거 없음", "collector_flag"),
    originCountry=F("베트남", "베트남", "HIGH",
        "상품명 '베트남 록렁 엑셀사 원두'",
        "audit-input/products/fillout-13732632561-6d9a976d.json#snapshotRecord.productName"),
    originRegion=F(None, "록렁", "SOURCE_MISSING",
        "'록렁' 토큰의 지역/농장 여부 확인 불가 — 무비판 승격 금지",
        "audit-input/products/fillout-13732632561-6d9a976d.json#snapshotRecord.productName"),
    producer=F(None, "록렁", "SOURCE_MISSING",
        "'록렁'이 생산자인지 확인 불가 — 무비판 승격 금지",
        "audit-input/products/fillout-13732632561-6d9a976d.json#snapshotRecord.productName"),
    process=F(None, None, "SOURCE_MISSING", "원문 확인했으나 가공 정보 없음",
        "audit-input/products/fillout-13732632561-6d9a976d.json#snapshotRecord.productName"),
    variety=F(None, "엑셀사", "SOURCE_MISSING",
        "상품명 '엑셀사'는 커피 종(species, 리베리카 계열)이지 품종(variety)이 아님 — §4 '자생종·다품종 같은 일반명은 품종이 아니다' 유추 적용",
        "audit-input/products/fillout-13732632561-6d9a976d.json#snapshotRecord.productName"),
    roast=F(None, None, "SOURCE_MISSING", "원문 확인했으나 로스팅 정보 없음",
        "audit-input/products/fillout-13732632561-6d9a976d.json#snapshotRecord.productName"),
    tastingNotes=F([], [], "SOURCE_MISSING",
        "OCR 출력 빈값 — 이미지 확인했으나 노트 정보 없음",
        "audit-input/products/fillout-13732632561-6d9a976d.json#evidence.ocr"),
)

# 5) namusairo-1146 (숨,결)
# current: country=과테말라(1개국만), process=무산소 내추럴(1종만), variety=버번/카투라(일부만) — 모두 원문보다 축소, 원문 우선
A["namusairo-1146"] = G(
    productType=F("blend", "숨,결", "HIGH",
        "원산지 'Ethiopia · Guatemala' 2개국 — §9 blend",
        "audit-input/products/namusairo-1146-0ed2bd94.json#evidence.rawObservations"),
    status=F("soldout", "SOLD OUT", "HIGH",
        "isSoldOut=true + 본문 'SOLD OUT' 표기",
        "audit-input/products/namusairo-1146-0ed2bd94.json#evidence.rawObservations"),
    originCountry=F("에티오피아 · 과테말라", "Ethiopia · Guatemala", "HIGH",
        "원문 '원산지 Ethiopia · Guatemala' — current는 과테말라 1개국만 있으나 원문 우선",
        "audit-input/products/namusairo-1146-0ed2bd94.json#evidence.rawObservations"),
    originRegion=F("함벨라 구지 · 예가체프 · 우에우에테낭고", "Hambela Guji ·Yirgacheffe · Huehuetenango", "HIGH",
        "원문 '지 역 Hambela Guji ·Yirgacheffe · Huehuetenango'",
        "audit-input/products/namusairo-1146-0ed2bd94.json#evidence.rawObservations"),
    producer=F(None, "벤티 넨카 · 게뎁 · 여러 소농들", "SOURCE_MISSING",
        "벤티 넨카/게뎁은 워싱스테이션명, 여러 소농들은 일반명 — 특정 생산자가 아니므로 제외 (초르소 선례)",
        "audit-input/products/namusairo-1146-0ed2bd94.json#evidence.rawObservations"),
    process=F("내추럴 · 무산소 내추럴 · 워시드", "Natural · Anaerobic Natural · Fully Washed", "HIGH",
        "원문 '가공법 Natural · Anaerobic Natural · Fully Washed' 3종 — current는 무산소 내추럴 1종만 있으나 원문 우선",
        "audit-input/products/namusairo-1146-0ed2bd94.json#evidence.rawObservations"),
    variety=F("74100 · 74112 · 월리쇼 · 쿠루메 · 데가 · JARC 74110 · 티피카 · 카투라 · 버본 · 카투아이 · 파체",
        "74100, 74112, Ethiopia Heirloom · Wolisho, Kurume, Dega, JARC 74110 · Typica, Caturra, Bourbon, Catuai, Paches", "HIGH",
        "원문 '품 종' 행 — 'Ethiopia Heirloom'은 자생종 계열 일반명이므로 제외 (§4). current는 버번/카투라 2종만 있으나 원문 우선",
        "audit-input/products/namusairo-1146-0ed2bd94.json#evidence.rawObservations"),
    roast=F("Dark", "다크 Dark", "HIGH",
        "원문 '볶음도 다크 Dark'",
        "audit-input/products/namusairo-1146-0ed2bd94.json#evidence.rawObservations"),
    tastingNotes=F(["블루베리", "시트러스", "브라운슈가", "버터스카치"],
        ["블루베리", "시트러스", "브라운슈가", "버터스카치", "풍부하고 편안한"], "HIGH",
        "원문 '향 미 블루베리, 시트러스, 브라운슈가, 버터스카치, 풍부하고 편안한' — '풍부하고 편안한'은 질감 서술로 value 제외·raw 보존",
        "audit-input/products/namusairo-1146-0ed2bd94.json#evidence.rawObservations"),
)

# 6) cafedoan-11754610521 (MANHATTAN Panama Aracelly Estribi)
# current: process/variety 비어 있음 — 원문에 워시드·게이샤 명시되므로 원문 우선 채택
A["cafedoan-11754610521"] = G(
    productType=F("single", "MANHATTAN 맨해튼 Panama Aracelly Estribi", "HIGH",
        "단일 산지(파나마) 명시",
        "audit-input/products/cafedoan-11754610521-6efb46fa.json#evidence.detailCache.detailText"),
    status=F("soldout", "soldout", "MEDIUM", "isSoldOut=true (수집 플래그), 반대 증거 없음", "collector_flag"),
    originCountry=F("파나마", "Panama", "HIGH",
        "원문 '파나마 아라셀리 에스트리비' / 'Panama Aracelly Estribi'",
        "audit-input/products/cafedoan-11754610521-6efb46fa.json#evidence.detailCache.detailText"),
    originRegion=F(None, "아라셀리 에스트리비", "SOURCE_MISSING",
        "'에스트리비'는 FST 농장의 구역 — 지역 승격 금지",
        "audit-input/products/cafedoan-11754610521-6efb46fa.json#evidence.detailCache.detailText"),
    producer=F("아라셀리 에스트리비", "Panama Aracelly Estribi", "MEDIUM",
        "상품명 농장/구역명 — 엘 파라이소 선례",
        "audit-input/products/cafedoan-11754610521-6efb46fa.json#snapshotRecord.productName"),
    process=F("워시드", "워시드 Washed", "HIGH",
        "원문 '파나마 아라셀리 에스트리비, 워시드' / 'Washed' — current는 비어 있으나 원문 우선",
        "audit-input/products/cafedoan-11754610521-6efb46fa.json#evidence.detailCache.detailText"),
    variety=F("게이샤", "게이샤 Geisha", "HIGH",
        "원문 '뛰어난 게이샤 Geisha 재배' — current는 비어 있으나 원문 우선",
        "audit-input/products/cafedoan-11754610521-6efb46fa.json#evidence.detailCache.detailText"),
    roast=F(None, None, "SOURCE_MISSING", "원문 확인했으나 로스팅 정보 없음 (Roast Date만 있음)",
        "audit-input/products/cafedoan-11754610521-6efb46fa.json#evidence.detailCache.detailText"),
    tastingNotes=F(["화이트 플라워", "레몬", "멜론"], ["화이트 플라워", "레몬", "멜론"], "HIGH",
        "원문 'CUP NOTE 화이트 플라워, 레몬, 멜론' — current의 '쥬시'는 질감 서술로 제외, '플로럴'은 화이트 플라워와 동일. OCR f80_80(복숭아·자스민·얼그레이·꿀)은 본문 및 f750_750과 충돌하므로 제외",
        "audit-input/products/cafedoan-11754610521-6efb46fa.json#evidence.detailCache.detailText"),
)

# 7) 루비아커피-시에나
A["루비아커피-시에나"] = G(
    productType=F("other", "시에나", "MEDIUM",
        "상품명 '시에나'만으로 유형 분류 불가 — 블렌드·싱글·디카페인 명시 없음 (§9 other)",
        "audit-input/products/루비아커피-시에나-b1abf8b4.json#snapshotRecord.productName"),
    status=F("active", "active", "MEDIUM", "isSoldOut=false (수집 플래그), 반대 증거 없음", "collector_flag"),
    originCountry=F(None, None, "SOURCE_MISSING", "원문 확인했으나 산지 정보 없음",
        "audit-input/products/루비아커피-시에나-b1abf8b4.json#evidence.detailCache.detailText"),
    originRegion=F(None, None, "SOURCE_MISSING", "원문 확인했으나 지역 정보 없음",
        "audit-input/products/루비아커피-시에나-b1abf8b4.json#evidence.detailCache.detailText"),
    producer=F(None, None, "SOURCE_MISSING", "원문 확인했으나 생산자 정보 없음",
        "audit-input/products/루비아커피-시에나-b1abf8b4.json#evidence.detailCache.detailText"),
    process=F(None, None, "SOURCE_MISSING", "원문 확인했으나 가공 정보 없음",
        "audit-input/products/루비아커피-시에나-b1abf8b4.json#evidence.detailCache.detailText"),
    variety=F(None, None, "SOURCE_MISSING", "원문 확인했으나 품종 정보 없음",
        "audit-input/products/루비아커피-시에나-b1abf8b4.json#evidence.detailCache.detailText"),
    roast=F(None, None, "SOURCE_MISSING", "원문 확인했으나 로스팅 정보 없음",
        "audit-input/products/루비아커피-시에나-b1abf8b4.json#evidence.detailCache.detailText"),
    tastingNotes=F(["바닐라", "견과류", "초콜릿"], ["#달콤한 바닐라", "#바닐라", "#견과류", "#초콜릿"], "MEDIUM",
        "OCR 단독 추출 (이미지2 해시태그 노트) — '#달콤한 바닐라'의 '달콤한'은 단맛 서술로 value 제외·raw 보존. 이미지3 '깔끔한 커피의 맛과 부드러운 바디감'은 질감 서술로 제외",
        "audit-input/products/루비아커피-시에나-b1abf8b4.json#evidence.ocr",
        evidenceKind="current_echo"),
)

# 8) fillout-13622467203 (콜롬비아 엘 엔칸토 게이샤 원두)
A["fillout-13622467203"] = G(
    productType=F("single", "콜롬비아 엘 엔칸토 게이샤 원두", "HIGH",
        "단일 산지(콜롬비아) 명시",
        "audit-input/products/fillout-13622467203-bd7ee90f.json#snapshotRecord.productName"),
    status=F("active", "active", "MEDIUM", "isSoldOut=false (수집 플래그), 반대 증거 없음", "collector_flag"),
    originCountry=F("콜롬비아", "콜롬비아", "HIGH",
        "상품명 '콜롬비아 엘 엔칸토 게이샤 원두'",
        "audit-input/products/fillout-13622467203-bd7ee90f.json#snapshotRecord.productName"),
    originRegion=F(None, "엘 엔칸토", "SOURCE_MISSING",
        "'엘 엔칸토'는 농장명으로 추정 — 지역 승격 금지",
        "audit-input/products/fillout-13622467203-bd7ee90f.json#snapshotRecord.productName"),
    producer=F("엘 엔칸토", "엘 엔칸토", "MEDIUM",
        "상품명 농장명 추정 (엘 파라이소 선례)",
        "audit-input/products/fillout-13622467203-bd7ee90f.json#snapshotRecord.productName"),
    process=F("워시드", "WASHED", "MEDIUM",
        "OCR 이미지 판독 'WASHED' — 상품명·본문에 가공 미명시이므로 MEDIUM",
        "audit-input/products/fillout-13622467203-bd7ee90f.json#evidence.ocr"),
    variety=F("게이샤", "게이샤", "HIGH",
        "상품명 '게이샤' 명시",
        "audit-input/products/fillout-13622467203-bd7ee90f.json#snapshotRecord.productName"),
    roast=F(None, None, "SOURCE_MISSING", "원문 확인했으나 로스팅 정보 없음",
        "audit-input/products/fillout-13622467203-bd7ee90f.json#snapshotRecord.productName"),
    tastingNotes=F(["플로럴", "열대과일"], ["플로럴", "열대과일", "달콤함"], "MEDIUM",
        "OCR 단독 추출 (이미지2: 플로럴·열대과일·달콤함) — '달콤함'은 단맛 서술로 value 제외·raw 보존",
        "audit-input/products/fillout-13622467203-bd7ee90f.json#evidence.ocr",
        evidenceKind="current_echo"),
)

# 9) namusairo-345 (브릴리)
# current: variety 비어 있음, notes 2종만 — 원문에 옐로우 버본·4종 노트 명시되므로 원문 우선
A["namusairo-345"] = G(
    productType=F("single", "브릴리", "HIGH",
        "원산지 'Brazil' 단일 산지 명시",
        "audit-input/products/namusairo-345-31503f41.json#evidence.rawObservations"),
    status=F("soldout", "SOLD OUT", "HIGH",
        "본문 내 'SOLD OUT' 표기 — isSoldOut=false와 충돌하나 원문 우선 (namusairo-522 선례)",
        "audit-input/products/namusairo-345-31503f41.json#evidence.rawObservations"),
    originCountry=F("브라질", "Brazil", "HIGH",
        "원문 '원산지 Brazil'",
        "audit-input/products/namusairo-345-31503f41.json#evidence.rawObservations"),
    originRegion=F("미나스제라이스", "미나스제라이스 Minas Gerais", "HIGH",
        "원문 '지 역 미나스제라이스 Minas Gerais'",
        "audit-input/products/namusairo-345-31503f41.json#evidence.rawObservations"),
    producer=F(None, "여러 소농들 Smallholders", "SOURCE_MISSING",
        "원문 '농 장 여러 소농들 Smallholders' — 특정 생산자가 아니므로 제외",
        "audit-input/products/namusairo-345-31503f41.json#evidence.rawObservations"),
    process=F("내추럴", "내추럴 Natural", "HIGH",
        "원문 '가공법 내추럴 Natural'",
        "audit-input/products/namusairo-345-31503f41.json#evidence.rawObservations"),
    variety=F("옐로우 버본", "옐로우 버본 Yellow Bourbon", "HIGH",
        "원문 '품 종 옐로우 버본 Yellow Bourbon' — current는 비어 있으나 원문 우선",
        "audit-input/products/namusairo-345-31503f41.json#evidence.rawObservations"),
    roast=F(None, "Well-done", "SOURCE_MISSING",
        "원문 '볶음도 Well-done' — 5단계 매핑표에 없음, enum 강제 금지 (batch-011/012 교훈)",
        "audit-input/products/namusairo-345-31503f41.json#evidence.rawObservations"),
    tastingNotes=F(["바닐라", "피스타치오", "크림브륄레", "밀크초콜릿"],
        ["바닐라", "피스타치오", "크림브륄레", "밀크초콜릿"], "HIGH",
        "원문 '향 미 바닐라, 피스타치오, 크림브륄레, 밀크초콜릿' — current는 바닐라·밀크초콜릿 2종만 있으나 원문 우선",
        "audit-input/products/namusairo-345-31503f41.json#evidence.rawObservations"),
)

# 10) aerycoffee-13695062103 ([에어리커피] 파나마 잔슨 하시엔다 26-112 게이샤 72h 퍼먼테이션 내추럴)
# current: process=내추럴 — '72h 퍼먼테이션'은 수식어이므로 핵심 가공 내추럴로 판정
A["aerycoffee-13695062103"] = G(
    productType=F("single", "[에어리커피] 파나마 잔슨 하시엔다 26-112 게이샤 72h 퍼먼테이션 내추럴", "HIGH",
        "단일 산지(파나마) 명시",
        "audit-input/products/aerycoffee-13695062103-d3e7d2ea.json#snapshotRecord.productName"),
    status=F("soldout", "soldout", "MEDIUM", "isSoldOut=true (수집 플래그), 반대 증거 없음", "collector_flag"),
    originCountry=F("파나마", "파나마", "HIGH",
        "상품명 '파나마 잔슨 하시엔다 26-112 게이샤 72h 퍼먼테이션 내추럴'",
        "audit-input/products/aerycoffee-13695062103-d3e7d2ea.json#snapshotRecord.productName"),
    originRegion=F(None, "잔슨 하시엔다 26-112", "SOURCE_MISSING",
        "'잔슨 하시엔다'는 농장명, '26-112'는 로트번호 — 지역 승격 금지",
        "audit-input/products/aerycoffee-13695062103-d3e7d2ea.json#snapshotRecord.productName"),
    producer=F("잔슨 하시엔다", "잔슨 하시엔다 26-112", "MEDIUM",
        "상품명 농장명(하시엔다 잔슨) — '26-112'는 로트번호이므로 제외",
        "audit-input/products/aerycoffee-13695062103-d3e7d2ea.json#snapshotRecord.productName"),
    process=F("내추럴", "72h 퍼먼테이션 내추럴", "HIGH",
        "'72h 퍼먼테이션'은 가공 수식어 — 핵심 가공은 내추럴 (원문 '72h 퍼먼테이션 내추럴')",
        "audit-input/products/aerycoffee-13695062103-d3e7d2ea.json#snapshotRecord.productName"),
    variety=F("게이샤", "게이샤", "HIGH",
        "상품명 '게이샤' 명시",
        "audit-input/products/aerycoffee-13695062103-d3e7d2ea.json#snapshotRecord.productName"),
    roast=F(None, None, "SOURCE_MISSING",
        "detailText는 로스팅 머신/로스팅일만 있고 로스팅 단계 정보 없음",
        "audit-input/products/aerycoffee-13695062103-d3e7d2ea.json#evidence.detailCache.detailText"),
    tastingNotes=F([], [], "SOURCE_MISSING", "원문 확인했으나 노트 정보 없음",
        "audit-input/products/aerycoffee-13695062103-d3e7d2ea.json#snapshotRecord.productName"),
)

# 11) cafedoan-13246237051 (NOMAD COFFEE 노마드 커피 Peru Timbuyacu Washed)
# current: notes=[견과류, 자두] — 원문 CUP NOTE는 '견과류, 노란 자두, 토피' 3종이므로 원문 우선
A["cafedoan-13246237051"] = G(
    productType=F("single", "NOMAD COFFEE 노마드 커피 Peru Timbuyacu Washed", "HIGH",
        "단일 산지(페루) 명시",
        "audit-input/products/cafedoan-13246237051-b911254c.json#evidence.detailCache.detailText"),
    status=F("soldout", "soldout", "MEDIUM", "isSoldOut=true (수집 플래그), 반대 증거 없음", "collector_flag"),
    originCountry=F("페루", "Peru", "HIGH",
        "원문 '페루 팀부야쿠' / 'Peru Timbuyacu'",
        "audit-input/products/cafedoan-13246237051-b911254c.json#evidence.detailCache.detailText"),
    originRegion=F(None, "팀부야쿠", "SOURCE_MISSING",
        "'팀부야쿠'는 농장명(원문 '그의 농장 팀부야쿠') — 지역 승격 금지",
        "audit-input/products/cafedoan-13246237051-b911254c.json#evidence.detailCache.detailText"),
    producer=F("팀부야쿠", "팀부야쿠 Timbuyacu", "MEDIUM",
        "원문 '그의 농장 팀부야쿠 Timbuyacu' — 농장 명시",
        "audit-input/products/cafedoan-13246237051-b911254c.json#evidence.detailCache.detailText"),
    process=F("워시드", "워시드 Washed", "HIGH",
        "원문 '페루 팀부야쿠, 워시드' / 'Washed'",
        "audit-input/products/cafedoan-13246237051-b911254c.json#evidence.detailCache.detailText"),
    variety=F(None, None, "SOURCE_MISSING", "원문 확인했으나 품종 정보 없음",
        "audit-input/products/cafedoan-13246237051-b911254c.json#evidence.detailCache.detailText"),
    roast=F(None, None, "SOURCE_MISSING", "원문 확인했으나 로스팅 정보 없음 (Roast Date만 있음)",
        "audit-input/products/cafedoan-13246237051-b911254c.json#evidence.detailCache.detailText"),
    tastingNotes=F(["견과류", "노란 자두", "토피"], ["견과류", "노란 자두", "토피"], "HIGH",
        "원문 'CUP NOTE 견과류, 노란 자두, 토피' — current는 토피 누락이나 원문 우선. OCR(f750_750)도 동일 노트 확인 → text_confirmed",
        "audit-input/products/cafedoan-13246237051-b911254c.json#evidence.detailCache.detailText"),
)

# 12) hocuspocus-11858895090 (탄자니아 템보 SL-28 AA 풀리 워시드)
# current: country 비어 있음 — 상품명에 탄자니아 명시되므로 원문 우선. notes에 옥수수 포함 (current 누락)
A["hocuspocus-11858895090"] = G(
    productType=F("single", "탄자니아 템보 SL-28 AA 풀리 워시드", "HIGH",
        "단일 산지(탄자니아) 명시",
        "audit-input/products/hocuspocus-11858895090-2a798dbb.json#snapshotRecord.productName"),
    status=F("soldout", "soldout", "MEDIUM", "isSoldOut=true (수집 플래그), 반대 증거 없음", "collector_flag"),
    originCountry=F("탄자니아", "탄자니아", "HIGH",
        "상품명 '탄자니아 템보 SL-28 AA 풀리 워시드' — current는 비어 있으나 원문 우선",
        "audit-input/products/hocuspocus-11858895090-2a798dbb.json#snapshotRecord.productName"),
    originRegion=F(None, "템보", "SOURCE_MISSING",
        "'템보' 토큰의 지역/농장 여부 확인 불가 — 무비판 승격 금지",
        "audit-input/products/hocuspocus-11858895090-2a798dbb.json#snapshotRecord.productName"),
    producer=F(None, "템보", "SOURCE_MISSING",
        "'템보'가 생산자인지 확인 불가 — 무비판 승격 금지",
        "audit-input/products/hocuspocus-11858895090-2a798dbb.json#snapshotRecord.productName"),
    process=F("워시드", "풀리 워시드", "HIGH",
        "상품명 '풀리 워시드' 명시",
        "audit-input/products/hocuspocus-11858895090-2a798dbb.json#snapshotRecord.productName"),
    variety=F("SL-28", "SL-28", "HIGH",
        "상품명 'SL-28' 명시 — 'AA'는 선별 등급이므로 제외",
        "audit-input/products/hocuspocus-11858895090-2a798dbb.json#snapshotRecord.productName"),
    roast=F(None, None, "SOURCE_MISSING", "원문 확인했으나 로스팅 정보 없음",
        "audit-input/products/hocuspocus-11858895090-2a798dbb.json#snapshotRecord.productName"),
    tastingNotes=F(["포도", "옥수수", "호두", "브라운슈가"], ["Grape", "Corn", "Walnut", "Brown Sugar"], "MEDIUM",
        "OCR 단독 추출 (이미지 텍스트) — current는 옥수수 누락이나 원문(OCR) 우선",
        "audit-input/products/hocuspocus-11858895090-2a798dbb.json#evidence.ocr",
        evidenceKind="current_echo"),
)

# 13) 루비아커피-과테말라세이바풀리워시드다크로스트
A["루비아커피-과테말라세이바풀리워시드다크로스트"] = G(
    productType=F("single", "과테말라 세이바 풀리 워시드 다크 로스트", "HIGH",
        "단일 산지(과테말라) 명시",
        "audit-input/products/루비아커피-과테말라세이바풀리워시드다크로스트-4294e0c7.json#snapshotRecord.productName"),
    status=F("active", "active", "MEDIUM", "isSoldOut=false (수집 플래그), 반대 증거 없음", "collector_flag"),
    originCountry=F("과테말라", "과테말라", "HIGH",
        "상품명 '과테말라 세이바 풀리 워시드 다크 로스트'",
        "audit-input/products/루비아커피-과테말라세이바풀리워시드다크로스트-4294e0c7.json#snapshotRecord.productName"),
    originRegion=F(None, "세이바", "SOURCE_MISSING",
        "'세이바'는 농장명으로 추정 — 지역 승격 금지",
        "audit-input/products/루비아커피-과테말라세이바풀리워시드다크로스트-4294e0c7.json#snapshotRecord.productName"),
    producer=F("세이바", "세이바", "MEDIUM",
        "상품명 농장명 추정 (엘 파라이소 선례)",
        "audit-input/products/루비아커피-과테말라세이바풀리워시드다크로스트-4294e0c7.json#snapshotRecord.productName"),
    process=F("워시드", "풀리 워시드", "HIGH",
        "상품명 '풀리 워시드' 명시",
        "audit-input/products/루비아커피-과테말라세이바풀리워시드다크로스트-4294e0c7.json#snapshotRecord.productName"),
    variety=F(None, None, "SOURCE_MISSING", "원문 확인했으나 품종 정보 없음",
        "audit-input/products/루비아커피-과테말라세이바풀리워시드다크로스트-4294e0c7.json#snapshotRecord.productName"),
    roast=F("Dark", "다크 로스트", "HIGH",
        "상품명 '다크 로스트' — 5단계 매핑표 Dark",
        "audit-input/products/루비아커피-과테말라세이바풀리워시드다크로스트-4294e0c7.json#snapshotRecord.productName"),
    tastingNotes=F(["카라멜", "초콜릿", "시트러스"], ["카라멜", "초콜릿", "시트러스", "묵직한", "복합미"], "MEDIUM",
        "서로 다른 이미지의 OCR 노트 병합 — '묵직한'·'복합미'는 질감·복합성 서술로 value 제외·raw 보존. current의 '묵직'도 동일 사유로 제외",
        "audit-input/products/루비아커피-과테말라세이바풀리워시드다크로스트-4294e0c7.json#evidence.ocr",
        evidenceKind="current_echo"),
)

# 14) fillout-13726114734 (콜롬비아 그란자 파라이소92 디카프 원두 (디카페인))
A["fillout-13726114734"] = G(
    productType=F("decaf", "콜롬비아 그란자 파라이소92 디카프 원두 (디카페인)", "HIGH",
        "상품명 '디카프', '(디카페인)' 명시",
        "audit-input/products/fillout-13726114734-4d3f7aea.json#snapshotRecord.productName"),
    decafMethod=F(None, None, "UNKNOWN",
        "디카페인 명시이나 가공법 미명시 — rev2 기준 UNKNOWN",
        "audit-input/products/fillout-13726114734-4d3f7aea.json#snapshotRecord.productName"),
    status=F("active", "active", "MEDIUM", "isSoldOut=false (수집 플래그), 반대 증거 없음", "collector_flag"),
    originCountry=F("콜롬비아", "콜롬비아", "HIGH",
        "상품명 '콜롬비아 그란자 파라이소92 디카프 원두 (디카페인)'",
        "audit-input/products/fillout-13726114734-4d3f7aea.json#snapshotRecord.productName"),
    originRegion=F(None, "그란자 파라이소92", "SOURCE_MISSING",
        "'그란자 파라이소92'는 농장명으로 보임 — 지역 승격 금지",
        "audit-input/products/fillout-13726114734-4d3f7aea.json#snapshotRecord.productName"),
    producer=F("그란자 파라이소92", "그란자 파라이소92", "MEDIUM",
        "상품명 농장명(Granja Paraíso 92)",
        "audit-input/products/fillout-13726114734-4d3f7aea.json#snapshotRecord.productName"),
    process=F(None, None, "SOURCE_MISSING", "원문 확인했으나 본래 가공 정보 없음 (디카페인 가공법도 미명시)",
        "audit-input/products/fillout-13726114734-4d3f7aea.json#snapshotRecord.productName"),
    variety=F(None, None, "SOURCE_MISSING", "원문 확인했으나 품종 정보 없음",
        "audit-input/products/fillout-13726114734-4d3f7aea.json#snapshotRecord.productName"),
    roast=F(None, None, "SOURCE_MISSING", "원문 확인했으나 로스팅 정보 없음",
        "audit-input/products/fillout-13726114734-4d3f7aea.json#snapshotRecord.productName"),
    tastingNotes=F([], [], "SOURCE_MISSING",
        "OCR 출력 빈값 — 이미지 확인했으나 노트 정보 없음",
        "audit-input/products/fillout-13726114734-4d3f7aea.json#evidence.ocr"),
)

# 15) namusairo-1136 (라에스메랄다 게샤)
A["namusairo-1136"] = G(
    productType=F("single", "라에스메랄다 게샤", "HIGH",
        "원산지 'Colombia' 단일 산지 명시",
        "audit-input/products/namusairo-1136-ba721afb.json#evidence.rawObservations"),
    status=F("soldout", "SOLD OUT", "HIGH",
        "본문 내 'SOLD OUT' 표기 — isSoldOut=false와 충돌하나 원문 우선",
        "audit-input/products/namusairo-1136-ba721afb.json#evidence.rawObservations"),
    originCountry=F("콜롬비아", "Colombia", "HIGH",
        "원문 '원산지 Colombia'",
        "audit-input/products/namusairo-1136-ba721afb.json#evidence.rawObservations"),
    originRegion=F("팔레스티나 · 우일라", "팔레스티나, 우일라 Huila, Palestina", "HIGH",
        "원문 '지 역 팔레스티나, 우일라 Huila, Palestina'",
        "audit-input/products/namusairo-1136-ba721afb.json#evidence.rawObservations"),
    producer=F("라에스메랄다", "라에스메랄다 La Esmeralda", "HIGH",
        "원문 '농 장 라에스메랄다 La Esmeralda' 명시",
        "audit-input/products/namusairo-1136-ba721afb.json#evidence.rawObservations"),
    process=F("워시드", "워시드 Washed", "HIGH",
        "원문 '가공법 워시드 Washed'",
        "audit-input/products/namusairo-1136-ba721afb.json#evidence.rawObservations"),
    variety=F("게이샤", "게이샤 Gesha", "HIGH",
        "원문 '품 종 게이샤 Gesha'",
        "audit-input/products/namusairo-1136-ba721afb.json#evidence.rawObservations"),
    roast=F("Light", "Light", "HIGH",
        "원문 '볶음도 Light'",
        "audit-input/products/namusairo-1136-ba721afb.json#evidence.rawObservations"),
    tastingNotes=F(["베르가못", "라임"], ["베르가못", "라임", "게샤 플레이버", "클래식"], "HIGH",
        "원문 '향 미 베르가못, 라임, 게샤 플레이버, 클래식' — '게샤 플레이버'는 품종 언급, '클래식'은 스타일 서술로 노트에서 제외·raw 보존",
        "audit-input/products/namusairo-1136-ba721afb.json#evidence.rawObservations"),
)

# 16) aerycoffee-13753047172 ([에어리커피] 에티오피아 고구구 74110 74112 74158 내추럴)
# current: variety 비어 있음 — 상품명에 품종 번호 명시되므로 원문 우선
A["aerycoffee-13753047172"] = G(
    productType=F("single", "[에어리커피] 에티오피아 고구구 74110 74112 74158 내추럴", "HIGH",
        "단일 산지(에티오피아) 명시",
        "audit-input/products/aerycoffee-13753047172-53ed80e6.json#snapshotRecord.productName"),
    status=F("active", "active", "MEDIUM", "isSoldOut=false (수집 플래그), 반대 증거 없음", "collector_flag"),
    originCountry=F("에티오피아", "에티오피아", "HIGH",
        "상품명 '에티오피아 고구구 74110 74112 74158 내추럴'",
        "audit-input/products/aerycoffee-13753047172-53ed80e6.json#snapshotRecord.productName"),
    originRegion=F(None, "고구구", "SOURCE_MISSING",
        "'고구구' 토큰의 지역/농장 여부 확인 불가 — 무비판 승격 금지",
        "audit-input/products/aerycoffee-13753047172-53ed80e6.json#snapshotRecord.productName"),
    producer=F(None, "고구구", "SOURCE_MISSING",
        "'고구구'가 생산자인지 확인 불가 — 무비판 승격 금지",
        "audit-input/products/aerycoffee-13753047172-53ed80e6.json#snapshotRecord.productName"),
    process=F("내추럴", "내추럴", "HIGH",
        "상품명 '내추럴' 명시",
        "audit-input/products/aerycoffee-13753047172-53ed80e6.json#snapshotRecord.productName"),
    variety=F("74110 · 74112 · 74158", "74110 74112 74158", "HIGH",
        "상품명 품종 번호 명시 — current는 비어 있으나 원문 우선",
        "audit-input/products/aerycoffee-13753047172-53ed80e6.json#snapshotRecord.productName"),
    roast=F(None, None, "SOURCE_MISSING",
        "detailText는 로스팅일(2026.09.17)만 있고 로스팅 단계 정보 없음",
        "audit-input/products/aerycoffee-13753047172-53ed80e6.json#evidence.detailCache.detailText"),
    tastingNotes=F([], [], "SOURCE_MISSING", "원문 확인했으나 노트 정보 없음",
        "audit-input/products/aerycoffee-13753047172-53ed80e6.json#snapshotRecord.productName"),
)

# 17) cafedoan-11754557408 (MANHATTAN Ecuador Pepe Jijón Syoxy)
# current: process/variety 비어 있음, region='MANHATTAN 맨해튼 Pepe Jijón Syoxy' — 원문에 타이옥시데이터 워시드·시드라 명시
A["cafedoan-11754557408"] = G(
    productType=F("single", "MANHATTAN 맨해튼 Ecuador Pepe Jijón Syoxy", "HIGH",
        "단일 산지(에콰도르) 명시",
        "audit-input/products/cafedoan-11754557408-04c95035.json#evidence.detailCache.detailText"),
    status=F("soldout", "soldout", "MEDIUM", "isSoldOut=true (수집 플래그), 반대 증거 없음", "collector_flag"),
    originCountry=F("에콰도르", "Ecuador", "HIGH",
        "원문 '에콰도르 페페 히욘' / 'Ecuador Pepe Jijón'",
        "audit-input/products/cafedoan-11754557408-04c95035.json#evidence.detailCache.detailText"),
    originRegion=F(None, None, "SOURCE_MISSING", "원문 확인했으나 지역 정보 없음",
        "audit-input/products/cafedoan-11754557408-04c95035.json#evidence.detailCache.detailText"),
    producer=F("페페 히욘", "페페 히욘 Pepe Jijón", "MEDIUM",
        "제품명 'Ecuador Pepe Jijón' — '맨해튼의 친구 페페 히욘으로부터 온 커피'. 핀카 솔레다드는 가공 농장이나 제품은 페페 히욘 명의",
        "audit-input/products/cafedoan-11754557408-04c95035.json#evidence.detailCache.detailText"),
    process=F("타이옥시데이터 워시드", "타이옥시데이터 워시드 Tyoxidator Washed", "HIGH",
        "원문 '타이옥시데이터 워시드' / 'Tyoxidator Washed' — current는 비어 있으나 원문 우선",
        "audit-input/products/cafedoan-11754557408-04c95035.json#evidence.detailCache.detailText"),
    variety=F("시드라", "시드라 Sidra", "HIGH",
        "원문 '시드라 Sidra 품종' — current는 비어 있으나 원문 우선",
        "audit-input/products/cafedoan-11754557408-04c95035.json#evidence.detailCache.detailText"),
    roast=F(None, None, "SOURCE_MISSING", "원문 확인했으나 로스팅 정보 없음",
        "audit-input/products/cafedoan-11754557408-04c95035.json#evidence.detailCache.detailText"),
    tastingNotes=F(["파파야", "홍차", "체리"], ["파파야", "홍차", "체리", "부드럽다"], "HIGH",
        "원문 'CUP NOTE 파파야, 홍차, 체리, 부드럽다' — '부드럽다'는 질감 서술로 value 제외·raw 보존. current의 '부드러움'도 동일 사유로 제외",
        "audit-input/products/cafedoan-11754557408-04c95035.json#evidence.detailCache.detailText"),
)

# 18) 루비아커피-브라질ny2세하도파인컵내추럴미디엄로스트
# current: notes=[구운향, 호두, 초콜릿] — '구운향'은 OCR에 없는 current 생성 노트. OCR process='Pupled Natural'(Pulped Natural) 표기를 원문으로 인정
A["루비아커피-브라질ny2세하도파인컵내추럴미디엄로스트"] = G(
    productType=F("single", "브라질 NY2 세하도 파인컵 내추럴 미디엄 로스트", "HIGH",
        "단일 산지(브라질) 명시",
        "audit-input/products/루비아커피-브라질ny2세하도파인컵내추럴미디엄로스트-e69c226d.json#snapshotRecord.productName"),
    status=F("active", "active", "MEDIUM", "isSoldOut=false (수집 플래그), 반대 증거 없음", "collector_flag"),
    originCountry=F("브라질", "브라질", "HIGH",
        "상품명 '브라질 NY2 세하도 파인컵 내추럴 미디엄 로스트'",
        "audit-input/products/루비아커피-브라질ny2세하도파인컵내추럴미디엄로스트-e69c226d.json#snapshotRecord.productName"),
    originRegion=F("세하도", "세하도", "HIGH",
        "세하도(Cerrado)=브라질 대표 커피 산지 — 원문 '세하도'",
        "audit-input/products/루비아커피-브라질ny2세하도파인컵내추럴미디엄로스트-e69c226d.json#snapshotRecord.productName"),
    producer=F(None, "NY2 파인컵", "SOURCE_MISSING",
        "NY2=스크린 사이즈 등급, 파인컵=컵 등급 — 생산자가 아님",
        "audit-input/products/루비아커피-브라질ny2세하도파인컵내추럴미디엄로스트-e69c226d.json#snapshotRecord.productName"),
    process=F("펄프드 내추럴", "Pupled Natural (내추럴)", "MEDIUM",
        "OCR 이미지 판독 'Pupled Natural'(Pulped Natural 오타) — 상품명의 '내추럴'보다 구체적인 이미지 원문 표기로 판정",
        "audit-input/products/루비아커피-브라질ny2세하도파인컵내추럴미디엄로스트-e69c226d.json#evidence.ocr"),
    variety=F(None, None, "SOURCE_MISSING", "원문 확인했으나 품종 정보 없음 (NY2=등급, 파인컵=등급)",
        "audit-input/products/루비아커피-브라질ny2세하도파인컵내추럴미디엄로스트-e69c226d.json#snapshotRecord.productName"),
    roast=F("Medium", "미디엄 로스트", "HIGH",
        "상품명 '미디엄 로스트' — 5단계 매핑표 Medium",
        "audit-input/products/루비아커피-브라질ny2세하도파인컵내추럴미디엄로스트-e69c226d.json#snapshotRecord.productName"),
    tastingNotes=F(["볶은 땅콩", "호두", "초콜릿"], ["Roasted Peanuts", "Walnut", "Chocolate"], "MEDIUM",
        "OCR 단독 추출 (이미지 텍스트) — current의 '구운향'은 OCR에 없는 current 생성 노트이므로 미채택",
        "audit-input/products/루비아커피-브라질ny2세하도파인컵내추럴미디엄로스트-e69c226d.json#evidence.ocr",
        evidenceKind="current_echo"),
)

# 19) fillout-13622501957 (예멘 베이트 야신 알케미 XI 원두)
# current: notes=[포도, 다크초콜릿] — 원문 OCR은 와인·포도·다크 초콜릿 3종이므로 원문 우선
A["fillout-13622501957"] = G(
    productType=F("single", "예멘 베이트 야신 알케미 XI 원두", "HIGH",
        "단일 산지(예멘) 명시",
        "audit-input/products/fillout-13622501957-942b014e.json#snapshotRecord.productName"),
    status=F("active", "active", "MEDIUM", "isSoldOut=false (수집 플래그), 반대 증거 없음", "collector_flag"),
    originCountry=F("예멘", "예멘", "HIGH",
        "상품명 '예멘 베이트 야신 알케미 XI 원두'",
        "audit-input/products/fillout-13622501957-942b014e.json#snapshotRecord.productName"),
    originRegion=F(None, "베이트 야신", "SOURCE_MISSING",
        "'베이트 야신' 토큰의 지역/농장 여부 확인 불가 — 무비판 승격 금지",
        "audit-input/products/fillout-13622501957-942b014e.json#snapshotRecord.productName"),
    producer=F(None, "베이트 야신", "SOURCE_MISSING",
        "'베이트 야신'이 생산자인지 확인 불가 — 무비판 승격 금지",
        "audit-input/products/fillout-13622501957-942b014e.json#snapshotRecord.productName"),
    process=F(None, None, "SOURCE_MISSING",
        "원문 확인했으나 가공 정보 없음 — OCR process='알케미'는 제품 라인명으로 보임",
        "audit-input/products/fillout-13622501957-942b014e.json#evidence.ocr"),
    variety=F(None, None, "SOURCE_MISSING", "원문 확인했으나 품종 정보 없음",
        "audit-input/products/fillout-13622501957-942b014e.json#snapshotRecord.productName"),
    roast=F(None, None, "SOURCE_MISSING", "원문 확인했으나 로스팅 정보 없음",
        "audit-input/products/fillout-13622501957-942b014e.json#snapshotRecord.productName"),
    tastingNotes=F(["와인", "포도", "다크 초콜릿"], ["와인", "포도", "다크 초콜릿"], "MEDIUM",
        "OCR 단독 추출 — current는 와인 누락이나 원문(OCR) 우선",
        "audit-input/products/fillout-13622501957-942b014e.json#evidence.ocr",
        evidenceKind="current_echo"),
)

# 20) namusairo-42 (와이칸 다크)
# current: variety=카투라/카투아이(2종만), notes=[다크초콜릿, 캐러멜, 체리] — 원문에 5품종·4노트(+서술) 명시되므로 원문 우선
A["namusairo-42"] = G(
    productType=F("single", "와이칸 다크", "HIGH",
        "원산지 'Guatemala' 단일 산지 명시",
        "audit-input/products/namusairo-42-1f9bda5e.json#evidence.rawObservations"),
    status=F("soldout", "SOLD OUT", "HIGH",
        "본문 내 'SOLD OUT' 표기 — isSoldOut=false와 충돌하나 원문 우선",
        "audit-input/products/namusairo-42-1f9bda5e.json#evidence.rawObservations"),
    originCountry=F("과테말라", "Guatemala", "HIGH",
        "원문 '원산지 Guatemala'",
        "audit-input/products/namusairo-42-1f9bda5e.json#evidence.rawObservations"),
    originRegion=F("우에우에테낭고", "우에우에테낭고 Huehuetenango", "HIGH",
        "원문 '지 역 우에우에테낭고 Huehuetenango'",
        "audit-input/products/namusairo-42-1f9bda5e.json#evidence.rawObservations"),
    producer=F(None, "여러 소농들 Smallholders", "SOURCE_MISSING",
        "원문 '농 장 여러 소농들 Smallholders' — 특정 생산자가 아니므로 제외",
        "audit-input/products/namusairo-42-1f9bda5e.json#evidence.rawObservations"),
    process=F("워시드", "Fully Washed", "HIGH",
        "원문 '가공법 Fully Washed'",
        "audit-input/products/namusairo-42-1f9bda5e.json#evidence.rawObservations"),
    variety=F("티피카 · 카투라 · 버본 · 카투아이 · 파체", "Typica, Caturra, Bourbon, Catuai, Paches", "HIGH",
        "원문 '품 종' 행 5종 — current는 카투라/카투아이 2종만 있으나 원문 우선",
        "audit-input/products/namusairo-42-1f9bda5e.json#evidence.rawObservations"),
    roast=F("Dark", "Dark", "HIGH",
        "원문 '볶음도 Dark'",
        "audit-input/products/namusairo-42-1f9bda5e.json#evidence.rawObservations"),
    tastingNotes=F(["다크 초콜릿", "블랙체리", "잼", "솔티드카라멜"],
        ["다크 초콜릿", "블랙체리", "잼", "솔티드카라멜", "깨끗하고 달다"], "HIGH",
        "원문 '향 미' 행 — '깨끗하고 달다'는 서술이므로 value 제외·raw 보존. current의 '캐러멜'은 솔티드카라멜 정규화, '체리'는 블랙체리 정규화로 보이나 '잼' 누락 — 원문 우선",
        "audit-input/products/namusairo-42-1f9bda5e.json#evidence.rawObservations"),
)

import os
out = os.path.expanduser("~/workspace/beanpick/audit/golden/_work/batch-013-reviewerA.json")
json.dump(A, open(out, "w"), ensure_ascii=False, indent=1)
print("wrote", out, len(A), "products")
