import type { Cafe24SourceConfig } from './cafe24OfficialAdapter';

export const OFFICIAL_MALL_CONFIGS: Record<string, Cafe24SourceConfig> = {
  fritz: {
    sourceId: 'fritz',
    roasterName: '프릳츠 커피 컴퍼니',
    sourceUrl: 'https://fritz.co.kr/product/list.html?cate_no=48',
    origin: 'https://fritz.co.kr',
    defaultWeight: 200,
    categoryNo: '48',
    trustCategoryAsBean: true,
    verifyStockFromDetail: true,
    blockedWords: ['드립백', '티백', '캡슐', '콜드브루', '선물', '쇼핑백', '수첩', '굿즈', '꿀꺽꿀꺽', '샷글라스'],
  },
  namusairo: {
    sourceId: 'namusairo',
    roasterName: '나무사이로',
    sourceUrl: 'https://namusairo.com/category/coffee/91/',
    origin: 'https://namusairo.com',
    defaultWeight: 200,
    categoryNo: '91',
    trustCategoryAsBean: true,
    verifyStockFromDetail: true,
    blockedWords: ['드립백', '파우치'],
  },
  coffeelibre: {
    sourceId: 'coffeelibre',
    roasterName: '커피리브레',
    sourceUrl: 'https://coffeelibre.kr/product/list.html?cate_no=47',
    origin: 'https://coffeelibre.kr',
    defaultWeight: 200,
    categoryNo: '47',
    trustCategoryAsBean: true,
    verifyStockFromDetail: true,
    blockedWords: ['생두'],
  },
  werk: {
    sourceId: 'werk',
    roasterName: '베르크커피',
    sourceUrl: 'https://werk.co.kr/',
    origin: 'https://werk.co.kr',
    defaultWeight: 200,
    verifyStockFromDetail: true,
    beanWords: ['럭키 베이비'],
    blockedWords: ['도매전용', '도매', '캡슐', '콜드브루', '인스턴트', '드립백', '기프트'],
  },
  deepbluelake: {
    sourceId: 'deepbluelake',
    roasterName: '딥블루레이크',
    sourceUrl: 'https://dblcoffee.com/product/list.html?cate_no=24',
    origin: 'https://dblcoffee.com',
    defaultWeight: 200,
    categoryNo: '24',
    verifyStockFromDetail: true,
    beanWords: ['블랜딩', '블렌딩', 'single origin'],
    blockedWords: ['드립백', '파우더', '유리컵', '컵'],
  },
  hellcafe: {
    sourceId: 'hellcafe',
    roasterName: '헬카페',
    sourceUrl: 'https://hellcafe.co.kr/store/store.html',
    origin: 'https://hellcafe.co.kr',
    defaultWeight: 200,
    categoryNo: '1',
    trustCategoryAsBean: true,
    verifyStockFromDetail: true,
    blockedWords: ['드립백', '콜드브루', '캡슐', '원액', '머그', '잔', '컵', '티셔츠', '굿즈'],
  },
  centercoffee: {
    sourceId: 'centercoffee',
    roasterName: '센터커피',
    sourceUrl: 'https://www.centercoffee.co.kr/67',
    origin: 'https://www.centercoffee.co.kr',
    defaultWeight: 200,
    parser: 'imweb',
    beanWords: ['블렌드', 'blend', 'geisha'],
    blockedWords: ['콜드브루', '드립백', '인스턴트', '캡슐', '스틱', '액상', '선물세트', '머그', '컵', '텀블러'],
  },
};
